import { Counter, Gauge, Histogram } from 'prom-client';

export const tokensFetched = new Counter({
  name: 'datahawk_tokens_fetched_total',
  help: 'Total tokens fetched by DataHawk',
  labelNames: ['source'],
});

export const signalsGenerated = new Gauge({
  name: 'datahawk_signals_generated_total',
  help: 'Total signals generated by DataHawk',
  labelNames: ['source'],
});

export const apiLatency = new Histogram({
  name: 'datahawk_api_latency_seconds',
  help: 'Latency of API requests',
  labelNames: ['api'],
  buckets: [0.1, 0.5, 1, 2, 5, 10],
});

export const errorRate = new Counter({
  name: 'datahawk_api_errors_total',
  help: 'Total API errors',
  labelNames: ['api'],
});

export const newsProcessed = new Counter({
  name: 'news_processed_total',
  help: 'Total news articles processed',
  labelNames: ['source', 'ticker'],
});

export const sentimentAccuracy = new Gauge({
  name: 'sentiment_accuracy',
  help: 'Accuracy of sentiment analysis',
  labelNames: ['ticker'],
});

export const announcementImpact = new Histogram({
  name: 'announcement_impact',
  help: 'Impact of announcements on tokens',
  labelNames: ['ticker'],
  buckets: [0.1, 0.3, 0.5, 0.7, 0.9, 1.0],
});

export const telegramAlertsSent = new Counter({
  name: 'datahawk_telegram_alerts_sent_total',
  help: 'Total Telegram alerts sent',
  labelNames: ['ticker'],
});

export const lunarcrushRequests = new Counter({
  name: 'datahawk_lunarcrush_requests_total',
  help: 'Total requests to LunarCrush API',
  labelNames: ['ticker'],
});

export const tickerExtraction = new Counter({
  name: 'datahawk_ticker_extraction_total',
  help: 'Total tickers extracted from text',
  labelNames: ['source'],
});

export const apiSwitch = new Counter({
  name: 'datahawk_api_switch_total',
  help: 'Total API switches due to errors',
  labelNames: ['api'],
});

export const lunarcrushRequestTime = new Histogram({
  name: 'datahawk_lunarcrush_request_time_seconds',
  help: 'Latency of LunarCrush API requests',
  labelNames: ['ticker'],
  buckets: [0.1, 0.5, 1, 2, 5, 10],
});

export const fibonacciExits = new Gauge({
  name: 'trades_fibonacci_exits_total',
  help: 'Total exits by Fibonacci levels',
  labelNames: ['ticker'],
});

export const trailingStopTriggered = new Counter({
  name: 'trailing_stop_triggered_total',
  help: 'Total trailing stop triggers',
  labelNames: ['ticker', 'exitReason'],
});

export const sentimentTrades = new Counter({
  name: 'trades_sentiment_total',
  help: 'Total trades based on sentiment signals',
  labelNames: ['ticker'],
});

export const telegramSignalsProcessed = new Counter({
  name: 'telegram_signals_processed_total',
  help: 'Total Telegram signals processed',
  labelNames: ['ticker'],
});

export const telegramApiErrors = new Counter({
  name: 'telegram_api_errors_total',
  help: 'Total Telegram API errors',
  labelNames: ['ticker'],
});

export const telegramCheckLatency = new Histogram({
  name: 'telegram_check_latency_seconds',
  help: 'Latency of Telegram API checks',
  labelNames: ['ticker'],
  buckets: [0.1, 0.5, 1, 2, 5, 10],
});

export const swarmCommandsProcessed = new Counter({
  name: 'swarm_commands_processed_total',
  help: 'Number of commands processed by SwarmMaster',
  labelNames: ['source', 'command'],
});

export const filterPerformance = new Counter({
  name: 'filter_performance_total',
  help: 'Performance of filters based on selected tokens',
  labelNames: ['filter', 'ticker'],
});

export const riskyTokensFiltered = new Counter({
  name: 'risky_tokens_filtered_total',
  help: 'Number of risky tokens filtered out',
  labelNames: ['ticker', 'reason'],
});

export const walletRebalance = new Counter({
  name: 'wallet_rebalance_total',
  help: 'Number of wallet rebalance operations',
  labelNames: ['walletId'],
});

export const coordinationRequestsTotal = new Counter({
  name: 'coordination_requests_total',
  help: 'Total coordination requests processed by SwarmMaster',
  labelNames: ['asset'],
});

export const tradesExecutedTotal = new Counter({
  name: 'trades_executed_total',
  help: 'Total number of executed trades',
  labelNames: ['ticker'],
});
