name: Lint and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Run ESLint
        run: npx eslint src/**/*.ts --fix
      - name: Build TypeScript
        run: npm run build
      - name: Commit Fixes
        if: github.event_name == 'push'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Apply ESLint fixes" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install Python Dependencies
        run: |
          pip install -r src/integrations/requirements_tweetcord.txt
          pip install -r src/integrations/requirements_telegramnews.txt
          pip install -r src/scrapers/requirements_lunarxcord.txt
          pip install -r src/scrapers/requirements_xalphacord.txt
      - name: Run Pylint
        run: |
          pip install pylint
          pylint src/integrations/*.py src/scrapers/*.py
